// list of all crops and seasons

import 'package:flutter/material.dart';

List<String> seasons = [
  'Kharif',
  'Whole Year',
  'Autumn',
  'Rabi',
  'Summer',
  'Winter'
];

List<String> crops = [
  'Arecanut',
  'Other Kharif pulses',
  'Rice',
  'Banana',
  'Cashewnut',
  'Coconut ',
  'Dry ginger',
  'Sugarcane',
  'Sweet potato',
  'Tapioca',
  'Black pepper',
  'Dry chillies',
  'other oilseeds',
  'Turmeric',
  'Maize',
  'Moong(Green Gram)',
  'Urad',
  'Arhar/Tur',
  'Groundnut',
  'Sunflower',
  'Bajra',
  'Castor seed',
  'Cotton(lint)',
  'Horse-gram',
  'Jowar',
  'Korra',
  'Ragi',
  'Tobacco',
  'Gram',
  'Wheat',
  'Masoor',
  'Sesamum',
  'Linseed',
  'Safflower',
  'Onion',
  'other misc. pulses',
  'Samai',
  'Small millets',
  'Coriander',
  'Potato',
  'Other  Rabi pulses',
  'Soyabean',
  'Beans & Mutter(Vegetable)',
  'Bhindi',
  'Brinjal',
  'Citrus Fruit',
  'Cucumber',
  'Grapes',
  'Mango',
  'Orange',
  'other fibres',
  'Other Fresh Fruits',
  'Other Vegetables',
  'Papaya',
  'Pome Fruit',
  'Tomato',
  'Mesta',
  'Cowpea(Lobia)',
  'Lemon',
  'Pome Granet',
  'Sapota',
  'Cabbage',
  'Rapeseed &Mustard',
  'Peas  (vegetable)',
  'Niger seed',
  'Bottle Gourd',
  'Varagu',
  'Garlic',
  'Ginger',
  'Oilseeds total',
  'Pulses total',
  'Jute',
  'Peas & beans (Pulses)',
  'Blackgram',
  'Paddy',
  'Pineapple',
  'Barley',
  'Sannhamp',
  'Khesari',
  'Guar seed',
  'Moth',
  'Other Cereals & Millets',
  'Cond-spcs other',
  'Turnip',
  'Carrot',
  'Redish',
  'Arcanut (Processed)',
  'Atcanut (Raw)',
  'Cashewnut Processed',
  'Cashewnut Raw',
  'Cardamom',
  'Rubber',
  'Bitter Gourd',
  'Drum Stick',
  'Jack Fruit',
  'Snak Guard',
  'Tea',
  'Coffee',
  'Cauliflower',
  'Other Citrus Fruit',
  'Water Melon',
  'Total foodgrain',
  'Kapas',
  'Colocosia',
  'Lentil',
  'Bean',
  'Jobster',
  'Perilla',
  'Rajmash Kholar',
  'Ricebean (nagadal)',
  'Ash Gourd',
  'Beet Root',
  'Lab-Lab',
  'Ribed Guard',
  'Yam',
  'Pump Kin',
  'Apple',
  'Peach',
  'Pear',
  'Plums',
  'Litchi',
  'Ber',
  'Other Dry Fruit',
  'Jute & mesta'
];

String cropsdata(int value) {
  return crops[value];
}

String seasonsdata(int value) {
  return seasons[value];
}
